---
title: "bcbio Native versus Cromwell results comparison"
author: "Sehrish Kanwal"
date: "`r format(Sys.time(), '%a %Y-%b-%d')`"
output:
  html_document: 
    keep_md: true
params:
  run_1: '/Users/kanwals/Documents/UMCCR/data/WTS_comparison/CCR180072_VPT_WH16/bcbio_native/run_1'
  run_2: '/Users/kanwals/Documents/UMCCR/data/WTS_comparison/CCR180072_VPT_WH16/bcbio_native/run_2'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE) # global setup
```

### Define functions.

```{r define_functions, comment=NA, message=FALSE, warning=FALSE}
###list files in a directory
lf <- function(...) {
  data.frame(fname = list.files(...)) %>% 
    knitr::kable(row.names = TRUE)
}

###count number of lines in a file
countLines <- function(file_names) {
  target_file <- data.frame(matrix(ncol = length(counts_file_name), nrow = 0))

  for (i in 1:length(file_names)) {
    if (file_ext(file_names[i]) == 'counts') {
      file <- read.table(file_names[i], sep="\t", as.is=TRUE, header=FALSE)
    } else {
      file <- read.table(file_names[i], sep="\t", as.is=TRUE, header=TRUE)
    }
    #count lines
    target_file <- rbind(target_file, data.frame(basename(file_names[i]), nrow(file)))
  }
  colnames(target_file) <- c("file", "lines_count")
  return(target_file)
}

###return different between input files
diffFiles <- function(file_names) {
  #an anti join returns the rows of the first table where it cannot find a match in the second table.
  #also pass a character vector of variables to join by.
  if (file_ext(file_names[1]) == 'counts') {
    input1 <- read.table(file_names[1], sep="\t", as.is=TRUE, header=FALSE)
    colnames(input1) <- c('gene_id', 'count')
    input2 <- read.table(file_names[2], sep="\t", as.is=TRUE, header=FALSE)
    colnames(input2) <- c('gene_id', 'count')
    join_by <- c('gene_id', 'count')
  } else {
    input1 <- read.table(file_names[1], sep="\t", as.is=TRUE, header=TRUE)
    input2 <- read.table(file_names[2], sep="\t", as.is=TRUE, header=TRUE)
    join_by <-  c('geneA.name', 'geneB.name', 'paircount', 'splitcount')
  }
  
  diff1 <- dplyr::anti_join(input1, input2, by = join_by) %>%
    mutate(input_info = 'run1') %>%
    dplyr::select(input_info, everything())
  
  diff2 <- dplyr::anti_join(input2, input1, by = join_by) %>%
    mutate(input_info = 'run2') %>%
    dplyr::select(input_info, everything())
  
  return(rbind(diff1,diff2))
}

```

### Required packages.

```{r, message=FALSE, warning=FALSE}
library(tools)
library(tidyr)
library(dplyr)
library(kableExtra)
library(diffobj)
```


### Read input. 

####The script expects two input directories, each containing 'final' results as produced by bcbio. The results in these two input directories will be compared.

```{r read_data, message=FALSE, warning=FALSE}
run_1 <-file.path(params$run_1)
#list files in the first run directory
lf(run_1)

run_2 <- file.path(params$run_2)
#list files in the second run directory
lf(run_2)

```

### Start with the simple line count in the files i.e. the number of entries in the output from both runs is same.

```{r count_lines, message=FALSE, warning=FALSE}
#compare the count files first (from both runs)
counts_file_name <- dir(c(run_1, run_2), pattern = ".counts")
counts_file_name[1] <-  paste(run_1, counts_file_name[1], sep = "/")
counts_file_name[2] <-  paste(run_2, counts_file_name[2], sep = "/")

#functionc call for calculating number of lines in count files from both runs
lines_count <- countLines(counts_file_name)
#function call for finding the differences between count files from both runs
diff_count <- diffFiles(counts_file_name)

#compare the fusion calls (from both runs)
fusions_file_name <- dir(c(run_1, run_2), pattern = "flat.tsv")
fusions_file_name[1] <-  paste(run_1, fusions_file_name[1], sep = "/")
fusions_file_name[2] <-  paste(run_2, fusions_file_name[2], sep = "/")

#functionc call for calculating number of lines in fusion files form both runs
lines_fusion <- countLines(fusions_file_name)
#function call for finding the differences between fusion calls from both runs
diff_fusion <- diffFiles(fusions_file_name)

```









